# src/trading_bot/strategy/engine.py

"""
Core Strategy Engine (Module 2).

This module defines the StrategyEngine, which is responsible for
orchestrating one or more trading strategies.
"""

import logging
from typing import List

from ..core.schemas import IngestionEngineOutput, TradeSignal
from .abc import BaseStrategy

# Get a logger for this module
logger = logging.getLogger(__name__)


class StrategyEngine:
    """
    Orchestrates all active trading strategies.

    This class adheres to the Single Responsibility Principle by
    delegating all trading *logic* to the injected strategy
    abstractions (implementations of BaseStrategy).

    Its only responsibility is to *coordinate* these strategies by:
    1. Receiving a single `IngestionEngineOutput` data packet.
    2. Passing this packet to every registered strategy.
    3. Collecting all `TradeSignal` objects generated by the strategies.

    This design follows the Dependency Inversion Principle, as it
    depends on the `BaseStrategy` abstraction, not on any concrete
    strategy implementation. This makes it highly extensible (Open/Closed
    Principle), as new strategies can be added without modifying this engine.
    """

    def __init__(self, strategies: List[BaseStrategy]):
        """
        Initializes the engine using Dependency Injection.

        :param strategies: A list of concrete implementations of
                           BaseStrategy (e.g., [DummyStrategy(),
                           KellyMomentumStrategy()]).
        """
        self.strategies = strategies
        if not strategies:
            logger.warning("StrategyEngine initialized with zero strategies.")
        else:
            strategy_names = ", ".join([s.name for s in self.strategies])
            logger.info(
                f"StrategyEngine initialized with {len(self.strategies)} "
                f"strategies: [{strategy_names}]"
            )

    def process_data_tick(self, data: IngestionEngineOutput) -> List[TradeSignal]:
        """
        Processes one "tick" of data from the Ingestion Engine.

        This method iterates through all registered strategies, calls their
        `evaluate` method with the new data, and collects all generated
        signals.

        This process is robust; a failure in one strategy will be logged
        but will not stop other strategies from being evaluated.

        :param data: The `IngestionEngineOutput` object for this tick,
                     containing all market and external data.
        :return: A list of all `TradeSignal` objects generated by all
                 strategies. This list may be empty if no strategies
                 produced a signal.
        """
        all_signals: List[TradeSignal] = []

        for strategy in self.strategies:
            try:
                # 2. Evaluate the strategy
                signals = strategy.evaluate(data)

                # 3. Collect and validate signals
                for signal in signals:
                    # Ensure the strategy correctly stamped its own name
                    if signal.strategy_name != strategy.name:
                        logger.warning(
                            f"Signal from strategy '{strategy.name}' has "
                            f"mismatched name: '{signal.strategy_name}'. "
                            "Correcting."
                        )
                        # Create a corrected copy of the signal
                        signal = signal.model_copy(
                            update={"strategy_name": strategy.name}
                        )

                    all_signals.append(signal)

                if signals:
                    logger.debug(
                        f"Strategy '{strategy.name}' generated "
                        f"{len(signals)} signals."
                    )

            except Exception as e:
                # 4. Isolate failures
                # Log the error but continue the loop
                logger.error(
                    f"Error during evaluation of strategy '{strategy.name}': {e}",
                    exc_info=True,  # Includes stack trace in log
                )

        if all_signals:
            logger.info(
                f"StrategyEngine generated a total of {len(all_signals)} "
                "signals this tick."
            )
        else:
            logger.debug("StrategyEngine generated 0 signals this tick.")

        return all_signals
