import logging
from datetime import datetime, timezone
from unittest.mock import patch

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker

# Import core components for setup
from trading_bot.core.database import Base
from trading_bot.core.enums import AlertSeverity, SignalType
from trading_bot.core.models import EventLog
from trading_bot.core.schemas import (
    MarketData,
    MarketDetails,
    OrderBook,
    PriceLevel,
    TradeSignal,
)

# Import the modules we are integrating
from trading_bot.monitoring import logger as logger_module
from trading_bot.monitoring.alerter import AlerterService, DatabaseAlerter
from trading_bot.risk_management.manager import RiskManager
from trading_bot.risk_management.portfolio import Portfolio
from trading_bot.risk_management.sizing.fixed_amount import FixedAmountSizer

# --- Fixtures ---


@pytest.fixture(scope="module")
def setup_logging_fixture():
    """
    Fixture to set up the global logger ONCE for this test module.
    We patch the settings to ensure a consistent log level.
    """
    # Store original state
    root_logger = logging.getLogger()
    original_handlers = root_logger.handlers[:]
    original_level = root_logger.level

    # Patch settings to use "INFO" level for this test
    with patch("trading_bot.config.settings", LOG_LEVEL="INFO"):
        logger_module.setup_logging()

    # Yield to let tests run
    yield

    # Teardown: Restore original logging state
    root_logger.handlers.clear()
    for handler in original_handlers:
        root_logger.addHandler(handler)
    root_logger.setLevel(original_level)


@pytest.fixture(scope="function")
def in_memory_db_session() -> Session:
    """
    Creates a real in-memory SQLite database session for each test.
    This ensures all tables (including EventLog) are created and fresh.
    """
    engine = create_engine("sqlite+pysqlite:///:memory:")
    Base.metadata.create_all(engine)  # Create all tables
    SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
        Base.metadata.drop_all(engine)


@pytest.fixture
def low_balance_portfolio() -> Portfolio:
    """A real Portfolio instance with only 50 USD."""
    # This portfolio is now asset-agnostic
    return Portfolio(initial_balance=50.0, quote_currency="USD")


@pytest.fixture
def standard_sizer() -> FixedAmountSizer:
    """A real sizer that wants to spend 100 USD."""
    return FixedAmountSizer(default_amount_usdc=100.0)


@pytest.fixture
def risk_manager_low_balance(
    low_balance_portfolio: Portfolio, standard_sizer: FixedAmountSizer
) -> RiskManager:
    """A real RiskManager wired with the low-balance portfolio."""
    return RiskManager(portfolio=low_balance_portfolio, sizer=standard_sizer)


@pytest.fixture
def mock_market_data() -> MarketData:
    """Returns mock market data for sizing."""
    return MarketData(
        market_id="MKT_01",
        order_book=OrderBook(
            bids=[PriceLevel(price=0.49, size=100)],
            asks=[PriceLevel(price=0.51, size=100)],
        ),
        recent_trades=[],
        details=MarketDetails(
            market_id="MKT_01",
            name="Test Market",
            end_date=datetime.now(timezone.utc),
            resolution_source="test",
        ),
    )


@pytest.fixture
def market_data_map(mock_market_data: MarketData) -> dict:
    """Returns a map containing the mock market data."""
    return {"MKT_01": mock_market_data}


@pytest.fixture
def mock_buy_signal() -> TradeSignal:
    """Returns a simple BUY signal."""
    return TradeSignal(
        market_id="MKT_01",
        strategy_name="test_strat",
        signal_type=SignalType.BUY,
        # 'outcome' is removed per 'complete_agnostic.diff'
        confidence=0.6,
    )


# --- Integration Test Cases ---


def test_risk_manager_generates_formatted_log(
    setup_logging_fixture,  # Ensures logger is configured
    risk_manager_low_balance: RiskManager,
    mock_buy_signal: TradeSignal,
    market_data_map: dict,
    caplog,  # Pytest fixture to capture log output
):
    """
    Tests the integration between RiskManager (Module 3) and Logger (Module 5).

    1.  Sets up the global logger.
    2.  Calls RiskManager.process_signal() which should fail on a balance check.
    3.  Asserts that the log message generated by RiskManager is captured
        and correctly formatted by the logger.
    """
    # --- Arrange ---
    # Set the caplog level to capture WARNING messages
    caplog.set_level(logging.WARNING)

    # --- Act ---
    # This call will fail the balance check:
    # Sizer wants $100, but portfolio only has $50.
    order = risk_manager_low_balance.process_signal(mock_buy_signal, market_data_map)

    # --- Assert ---
    # 1. No order should be created
    assert order is None

    # 2. A log record should have been captured
    assert len(caplog.records) == 1
    record = caplog.records[0]

    # 3. Check the log content (from RiskManager)
    assert record.levelname == "WARNING"
    assert "exceeds available" in record.message
    assert "Cost $100.00" in record.message
    assert "balance $50.00" in record.message

    # 4. Check the log source
    assert record.name == "trading_bot.risk_management.manager"

    # 5. Check the log formatting (from Logger)
    # We can't check the timestamp easily, but we know the logger adds it.
    # We can check the full formatted message.
    assert "WARNING" in caplog.text
    assert "trading_bot.risk_management.manager" in caplog.text
    assert "exceeds available balance" in caplog.text


def test_alerter_service_integrates_with_database(
    in_memory_db_session: Session,  # Our real, shared database
):
    """
    Tests the integration of the AlerterService (Module 5) with the
    shared database (Core Module).

    1.  Initializes an AlerterService with a DatabaseAlerter.
    2.  Calls the `notify` method.
    3.  Asserts that a new `EventLog` record is successfully created
        in the in-memory database.
    """
    # --- Arrange ---
    db = in_memory_db_session

    # 1. Create the DatabaseAlerter
    db_alerter = DatabaseAlerter()

    # 2. Create the AlerterService and inject the handler
    service = AlerterService(handlers=[db_alerter])

    # 3. Define the alert content
    message = "CRITICAL: Execution handler failed"
    severity = AlertSeverity.CRITICAL
    module = "ExecutionEngine"

    # --- Act ---
    # Send the notification
    service.notify(db, message, severity, module)

    # --- Assert ---
    # 1. Query the database to find the log entry
    log_entry = db.query(EventLog).one_or_none()

    # 2. Verify the entry exists and its data is correct
    assert log_entry is not None
    assert log_entry.severity == AlertSeverity.CRITICAL
    assert log_entry.message == "ExecutionEngine: CRITICAL: Execution handler failed"
    assert log_entry.source_module == "ExecutionEngine"
    assert log_entry.id == 1
