# src/trading_bot/risk_management/portfolio.py

import logging
from typing import Dict

from sqlalchemy.orm import Session

from ..core.enums import OrderSide, OrderStatus, PositionStatus

# Alias the ORM model to avoid name collision with the Pydantic schema
from ..core.models import Position as PositionModel
from ..core.schemas import (
    ExecutionResult,
    MarketData,
    OrderRequest,
    PortfolioState,
    Position,
)

logger = logging.getLogger(__name__)


class Portfolio:
    """
    Manages the in-memory state of the bot's positions and balances.

    This class is agnostic to the specific exchange and operates
    purely on the abstract data contracts (schemas). It is responsible
    for tracking assets, calculating P&L, and providing a snapshot
    of the current portfolio state.
    """

    def __init__(self, initial_balance_usdc: float):
        """
        Initializes the portfolio with a starting balance.

        :param initial_balance_usdc: The total starting capital in USDC.
        """
        self._cash_balance: float = initial_balance_usdc

        # In-memory state
        # Key: market_id (str) -> Position schema
        # The (market_id, outcome) tuple key has been replaced.
        self._positions: Dict[str, Position] = {}
        # Key: order_id -> OrderRequest schema
        self._open_orders: Dict[str, OrderRequest] = {}

        logger.info(f"Portfolio initialized with cash: {initial_balance_usdc:.2f} USDC")

    def load_positions(self, db: Session) -> None:
        """
        Loads all open positions from the database into memory.
        This should be called once on startup.

        :param db: The SQLAlchemy database session.
        """
        open_positions = (
            db.query(PositionModel).filter_by(status=PositionStatus.OPEN).all()
        )

        count = 0
        for pos_model in open_positions:
            pos_schema = Position(
                market_id=pos_model.market_id,
                size=pos_model.size,
                entry_price=pos_model.entry_price,
            )
            # The key is now just the market_id
            key = pos_schema.market_id
            self._positions[key] = pos_schema
            count += 1

        logger.info(f"Loaded {count} open positions from database.")

    def add_open_order(self, order_id: str, order: OrderRequest) -> None:
        """
        Adds an order to the in-memory list of open orders.
        This is used to calculate available balance.

        This method should be called by the Execution Engine *after*
        it has created a unique order_id for tracking.

        :param order_id: The unique order ID generated by the execution engine.
        :param order: The OrderRequest schema object.
        """
        if order_id in self._open_orders:
            logger.warning(f"Order {order_id} already tracked.")
            return
        self._open_orders[order_id] = order
        logger.debug(f"Added open order {order_id} to portfolio.")

    def update_order_status(self, db: Session, result: ExecutionResult) -> None:
        """
        Updates the portfolio state based on an execution result.
        This is the primary method for processing fills, cancels, or failures.
        This logic is now fully agnostic of 'outcome'.

        :param db: The SQLAlchemy database session for persistence.
        :param result: The ExecutionResult schema object from the engine.
        """
        # Remove order from tracking, whether filled or failed
        order = self._open_orders.pop(result.order_id, None)

        if result.status in (
            OrderStatus.CANCELLED,
            OrderStatus.REJECTED,
            OrderStatus.FAILED,
        ):
            logger.info(
                f"Order {result.order_id} finalized with status: {result.status}"
            )
            return

        # This logic assumes a final 'FILLED' status.
        # A more complex implementation would handle PARTIALLY_FILLED.
        if result.status != OrderStatus.FILLED:
            if order:
                self._open_orders[result.order_id] = order  # Put it back
            logger.warning(
                f"Received non-final status {result.status} for {result.order_id}. "
                "Portfolio will not update until FILLED."
            )
            return

        if order is None:
            logger.error(
                f"Received fill for untracked order {result.order_id}. "
                "State may be inconsistent."
            )
            return

        # --- Process the Fill (Agnostic Logic) ---
        fill_cost = result.filled_size * result.avg_price
        key = order.market_id
        pos = self._positions.get(key)
        realized_pnl = 0.0
        trade_size = result.filled_size
        trade_price = result.avg_price

        # Signed size: positive for BUY, negative for SELL
        trade_delta = trade_size if order.side == OrderSide.BUY else -trade_size

        # Adjust cash balance based on trade
        if order.side == OrderSide.BUY:
            self._cash_balance -= fill_cost
        else:  # SELL
            self._cash_balance += fill_cost

        if pos is None:  # Opening a new position
            pos = Position(
                market_id=order.market_id,
                size=trade_delta,
                entry_price=trade_price,
            )
            self._positions[key] = pos
            self._persist_position(db, pos, create=True)

        else:  # Modifying an existing position
            old_size = pos.size
            new_size = old_size + trade_delta

            is_flipping = (old_size * new_size) < 0
            is_adding = abs(new_size) > abs(old_size)
            is_reducing = abs(new_size) < abs(old_size) and not is_flipping

            if is_adding:
                # Calculate new average entry price
                old_value = abs(old_size) * pos.entry_price
                new_trade_value = trade_size * trade_price
                new_avg_price = (old_value + new_trade_value) / abs(new_size)
                pos.entry_price = new_avg_price
                pos.size = new_size

            elif is_reducing:
                # Realize P&L, entry price remains the same
                if old_size > 0:  # Closing part of a long
                    realized_pnl = trade_size * (trade_price - pos.entry_price)
                else:  # Closing part of a short
                    realized_pnl = trade_size * (pos.entry_price - trade_price)
                self._cash_balance += realized_pnl
                pos.size = new_size

            elif is_flipping:
                # Realize P&L on the closed portion, set new entry price
                size_closed = abs(old_size)
                if old_size > 0:  # Flipping long to short
                    realized_pnl = size_closed * (trade_price - pos.entry_price)
                else:  # Flipping short to long
                    realized_pnl = size_closed * (pos.entry_price - trade_price)
                self._cash_balance += realized_pnl
                pos.size = new_size
                pos.entry_price = trade_price  # New entry price is the flip price

            # Check if position was closed out
            if abs(new_size) < 1e-9:
                self._positions.pop(key)
                self._persist_position(db, pos, delete=True)
            else:
                self._persist_position(db, pos, update=True)

        logger.info(
            f"Fill processed for order {result.order_id}. "
            f"Market: {key}, New Size: {pos.size if pos else 0:.4f}. "
            f"Realized P&L: {realized_pnl:.2f}. New cash: {self._cash_balance:.2f}"
        )

    def _persist_position(
        self,
        db: Session,
        pos_schema: Position,
        create: bool = False,
        update: bool = False,
        delete: bool = False,
    ):
        """
        Handles the database persistence logic for a single position.

        :param db: The SQLAlchemy database session.
        :param pos_schema: The Pydantic Position schema to persist.
        :param create: Flag to create a new record.
        :param update: Flag to update an existing record.
        :param delete: Flag to mark a record as CLOSED.
        """
        # Query by market_id only, 'outcome' is removed
        pos_model = (
            db.query(PositionModel).filter_by(market_id=pos_schema.market_id).first()
        )

        try:
            if delete:
                if pos_model:
                    pos_model.status = PositionStatus.CLOSED
                    pos_model.size = 0
            elif create and not pos_model:
                pos_model = PositionModel(
                    market_id=pos_schema.market_id,
                    # 'outcome' removed
                    size=pos_schema.size,
                    entry_price=pos_schema.entry_price,
                    status=PositionStatus.OPEN,
                )
                db.add(pos_model)
            elif (update or create) and pos_model:
                pos_model.size = pos_schema.size
                pos_model.entry_price = pos_schema.entry_price
                pos_model.status = PositionStatus.OPEN

            db.commit()
        except Exception as e:
            logger.error(f"Failed to persist position for {pos_schema.market_id}: {e}")
            db.rollback()

    def calculate_unrealized_pnl(
        self, market_data_map: Dict[str, MarketData]
    ) -> Dict[str, float]:
        """
        Calculates the unrealized P&L for all open positions.

        :param market_data_map: A map of market_id to MarketData.
        :return: A dictionary mapping market_id to its unrealized P&L.
        """
        pnl_map = {}
        for key, pos in self._positions.items():
            # key is now market_id
            market_data = market_data_map.get(pos.market_id)
            current_price = pos.entry_price  # Default to no P&L

            if market_data:
                try:
                    # If long (size > 0), we'd sell (use best bid)
                    if pos.size > 0 and market_data.order_book.bids:
                        current_price = market_data.order_book.bids[0].price
                    # If short (size < 0), we'd buy (use best ask)
                    elif pos.size < 0 and market_data.order_book.asks:
                        current_price = market_data.order_book.asks[0].price
                except IndexError:
                    pass  # No liquidity, use entry price

            unrealized_pnl = pos.size * (current_price - pos.entry_price)
            pnl_map[key] = unrealized_pnl

        return pnl_map

    def get_state(self, market_data_map: Dict[str, MarketData]) -> PortfolioState:
        """
        Generates a snapshot of the current portfolio state.

        :param market_data_map: A dictionary mapping market_id to its
                                latest MarketData, used for pricing.
        :return: A PortfolioState schema object.
        """
        # 1. Calculate cash committed to open BUY orders
        committed_cash = 0.0
        open_orders_list = list(self._open_orders.values())
        for order in open_orders_list:
            if order.side == OrderSide.BUY:
                committed_cash += order.size * order.price

        available_balance = self._cash_balance - committed_cash

        # 2. Calculate total market value of all positions
        total_market_value = 0.0
        positions_list = list(self._positions.values())
        unrealized_pnl_map = self.calculate_unrealized_pnl(market_data_map)

        for pos in positions_list:
            # key is now just market_id
            key = pos.market_id
            pnl = unrealized_pnl_map.get(key, 0.0)
            # Market value is size * current_price.
            # (size * entry) + (size * (current - entry)) = size * current
            # We can get current_price from the P&L map logic
            cost_basis = pos.size * pos.entry_price
            market_value = cost_basis + pnl
            total_market_value += market_value

        # 3. Total balance = current cash + current market value of positions
        total_balance = self._cash_balance + total_market_value

        return PortfolioState(
            total_balance_usdc=total_balance,
            available_balance_usdc=available_balance,
            positions=positions_list,
            open_orders=open_orders_list,
        )
