# src/trading_bot/risk_management/portfolio.py

import logging
from typing import Dict, Optional

from sqlalchemy.orm import Session

from ..core.enums import OrderSide, OrderStatus
from ..core.repository import OrderRepository, PositionRepository
from ..core.schemas import (
    ExecutionResult,
    MarketData,
    OrderRequest,
    PortfolioState,
    Position,
)

logger = logging.getLogger(__name__)


class Portfolio:
    """
    Manages the in-memory state of the bot's positions and balances.

    This class is agnostic to the specific exchange and operates
    purely on the abstract data contracts (schemas). It is responsible
    for tracking assets, calculating P&L, and providing a snapshot
    of the current portfolio state.
    """

    def __init__(
        self,
        initial_balance: float,
        quote_currency: str = "USD",
        pos_repo: Optional[PositionRepository] = None,
        order_repo: Optional[OrderRepository] = None,
    ) -> None:
        """
        Initializes the portfolio with a starting balance and optional repositories.

        :param initial_balance: The total starting capital in the quote currency.
        :param quote_currency: The primary currency for accounting (e.g., "USD").
        :param pos_repo: Decoupled repository for Position db operations.
        :param order_repo: Decoupled repository for Order db operations.
        """
        self._cash_balance: float = initial_balance
        self.quote_currency: str = quote_currency
        self.pos_repo = pos_repo
        self.order_repo = order_repo

        # In-memory state
        # Key: f"{market_id}:{outcome}" if outcome else market_id
        self._positions: Dict[str, Position] = {}
        # Key: order_id -> OrderRequest schema
        self._open_orders: Dict[str, OrderRequest] = {}

        logger.info(
            f"Portfolio initialized with cash: {initial_balance:.2f} "
            f"{self.quote_currency}"
        )

    def load_positions(self, db: Optional[Session] = None) -> None:
        """
        Loads all open positions from the database into memory.
        This should be called once on startup.

        :param db: The optional SQLAlchemy database session for backwards compatibility.
        """
        repo = self.pos_repo or (PositionRepository(db) if db else None)
        if not repo:
            logger.warning(
                "No PositionRepository or Session provided to load_positions."
            )
            return

        open_positions = repo.get_open_positions()

        count = 0
        self._positions.clear()
        for pos_schema in open_positions:
            key = (
                f"{pos_schema.market_id}:{pos_schema.outcome}"
                if pos_schema.outcome
                else pos_schema.market_id
            )
            self._positions[key] = pos_schema
            count += 1

        logger.info(f"Loaded {count} open positions from repository.")

    def add_open_order(self, order_id: str, order: OrderRequest) -> None:
        """
        Adds an order to the in-memory list of open orders.
        This is used to calculate available balance.

        :param order_id: The unique order ID generated by the execution engine.
        :param order: The OrderRequest schema object.
        """
        if order_id in self._open_orders:
            logger.warning(f"Order {order_id} already tracked.")
            return
        self._open_orders[order_id] = order
        logger.debug(f"Added open order {order_id} to portfolio.")

    def update_order_status(
        self, db: Optional[Session], result: ExecutionResult
    ) -> None:
        """
        Updates the portfolio state based on an execution result.
        This is the primary method for processing fills, cancels, or failures.

        :param db: The optional SQLAlchemy database session for persistence.
        :param result: The ExecutionResult schema object from the engine.
        """
        # Resolve repositories
        active_pos_repo = self.pos_repo or (PositionRepository(db) if db else None)
        active_order_repo = self.order_repo or (OrderRepository(db) if db else None)

        # Remove order from tracking, whether filled or failed
        order = self._open_orders.pop(result.order_id, None)

        # Update order log in database
        if active_order_repo:
            active_order_repo.update_order(
                order_id=result.order_id,
                status=result.status,
                filled_size=result.filled_size,
                avg_fill_price=result.avg_price,
            )

        if result.status in (
            OrderStatus.CANCELLED,
            OrderStatus.REJECTED,
            OrderStatus.FAILED,
        ):
            logger.info(
                f"Order {result.order_id} finalized with status: {result.status}"
            )
            return

        if result.status != OrderStatus.FILLED:
            if order:
                self._open_orders[result.order_id] = order  # Put it back
            logger.warning(
                f"Received non-final status {result.status} for {result.order_id}. "
                "Portfolio will not update until FILLED."
            )
            return

        if order is None:
            logger.error(
                f"Received fill for untracked order {result.order_id}. "
                "State may be inconsistent."
            )
            return

        # --- Process the Fill (Agnostic / Outcome-aware Logic) ---
        fill_cost = result.filled_size * result.avg_price
        key = f"{order.market_id}:{order.outcome}" if order.outcome else order.market_id
        pos = self._positions.get(key)
        realized_pnl = 0.0
        trade_size = result.filled_size
        trade_price = result.avg_price

        # Signed size: positive for BUY, negative for SELL
        trade_delta = trade_size if order.side == OrderSide.BUY else -trade_size

        # Adjust cash balance based on trade
        if order.side == OrderSide.BUY:
            self._cash_balance -= fill_cost
        else:  # SELL
            self._cash_balance += fill_cost

        if pos is None:  # Opening a new position
            pos = Position(
                market_id=order.market_id,
                outcome=order.outcome,
                size=trade_delta,
                entry_price=trade_price,
            )
            self._positions[key] = pos
            if active_pos_repo:
                active_pos_repo.save_position(pos)

        else:  # Modifying an existing position
            old_size = pos.size
            new_size = old_size + trade_delta

            is_flipping = (old_size * new_size) < 0
            is_adding = abs(new_size) > abs(old_size)
            is_reducing = abs(new_size) < abs(old_size) and not is_flipping

            if is_adding:
                # Calculate new average entry price
                old_value = abs(old_size) * pos.entry_price
                new_trade_value = trade_size * trade_price
                new_avg_price = (old_value + new_trade_value) / abs(new_size)
                pos.entry_price = new_avg_price
                pos.size = new_size

            elif is_reducing:
                # Realize P&L, entry price remains the same
                if old_size > 0:  # Closing part of a long
                    realized_pnl = trade_size * (trade_price - pos.entry_price)
                else:  # Closing part of a short
                    realized_pnl = trade_size * (pos.entry_price - trade_price)
                pos.size = new_size

            elif is_flipping:
                # Realize P&L on the closed portion, set new entry price
                size_closed = abs(old_size)
                if old_size > 0:  # Flipping long to short
                    realized_pnl = size_closed * (trade_price - pos.entry_price)
                else:  # Flipping short to long
                    realized_pnl = size_closed * (pos.entry_price - trade_price)
                pos.size = new_size
                pos.entry_price = trade_price  # New entry price is the flip price

            # Check if position was closed out
            if abs(new_size) < 1e-9:
                self._positions.pop(key)
                if active_pos_repo:
                    active_pos_repo.save_position(pos, is_delete=True)
            else:
                if active_pos_repo:
                    active_pos_repo.save_position(pos)

        logger.info(
            f"Fill processed for order {result.order_id}. "
            f"Market: {key}, New Size: {pos.size if pos else 0:.4f}. "
            f"Realized P&L: {realized_pnl:.2f}. New cash: {self._cash_balance:.2f}"
        )

    def calculate_unrealized_pnl(
        self, market_data_map: Dict[str, MarketData]
    ) -> Dict[str, float]:
        """
        Calculates the unrealized P&L for all open positions.

        :param market_data_map: A map of market_id to MarketData.
        :return: A dictionary mapping position keys to their unrealized P&L.
        """
        pnl_map = {}
        for key, pos in self._positions.items():
            market_data = market_data_map.get(pos.market_id)
            current_price = pos.entry_price  # Default to no P&L

            if market_data:
                try:
                    # If long (size > 0), we'd sell (use best bid)
                    if (
                        pos.size > 0
                        and market_data.order_book
                        and market_data.order_book.bids
                    ):
                        current_price = market_data.order_book.bids[0].price
                    # If short (size < 0), we'd buy (use best ask)
                    elif (
                        pos.size < 0
                        and market_data.order_book
                        and market_data.order_book.asks
                    ):
                        current_price = market_data.order_book.asks[0].price
                except IndexError:
                    pass  # No liquidity, use entry price

            unrealized_pnl = pos.size * (current_price - pos.entry_price)
            pnl_map[key] = unrealized_pnl

        return pnl_map

    def get_state(self, market_data_map: Dict[str, MarketData]) -> PortfolioState:
        """
        Generates a snapshot of the current portfolio state.

        :param market_data_map: A dictionary mapping market_id to its
                                latest MarketData, used for pricing.
        :return: A PortfolioState schema object.
        """
        # 1. Calculate cash committed to open BUY orders
        committed_cash = 0.0
        open_orders_list = list(self._open_orders.values())
        for order in open_orders_list:
            if order.side == OrderSide.BUY:
                committed_cash += order.size * order.price

        available_balance = self._cash_balance - committed_cash

        # 2. Calculate total market value of all positions
        total_market_value = 0.0
        positions_list = list(self._positions.values())
        unrealized_pnl_map = self.calculate_unrealized_pnl(market_data_map)

        for pos in positions_list:
            key = f"{pos.market_id}:{pos.outcome}" if pos.outcome else pos.market_id
            pnl = unrealized_pnl_map.get(key, 0.0)
            cost_basis = pos.size * pos.entry_price
            market_value = cost_basis + pnl
            total_market_value += market_value

        # 3. Total balance = current cash + current market value of positions
        total_balance = self._cash_balance + total_market_value

        return PortfolioState(
            total_balance_quote=total_balance,
            available_balance_quote=available_balance,
            positions=positions_list,
            open_orders=open_orders_list,
        )
