# src/trading_bot/core/enums.py

from enum import Enum


class OrderSide(str, Enum):
    """
    Represents the side of an order.

    Used by the Execution Engine and for logging trades.
    """

    BUY = "buy"
    SELL = "sell"


class SignalType(str, Enum):
    """
    Represents the trading signal generated by the Strategy Engine.

    - BUY: A signal to enter a long position.
    - SELL: A signal to enter a short position (or exit a long).
    - HOLD: A signal to take no action.
    """

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class OrderStatus(str, Enum):
    """
    Represents the lifecycle state of an order sent to the exchange.

    Used by the Execution Engine and Portfolio Manager.
    """

    PENDING = "pending"  # Order created but not yet sent
    OPEN = "open"  # Order sent and active in the order book
    FILLED = "filled"  # Order has been completely filled
    PARTIALLY_FILLED = "partially_filled"  # Order has been partially filled
    CANCELLED = "cancelled"  # Order was cancelled
    REJECTED = "rejected"  # Order was rejected by the exchange
    FAILED = "failed"  # Order failed due to an on-chain or API error


class SizingStrategyType(str, Enum):
    """
    Enumeration of the supported position sizing strategies.
    """

    KELLY_CRITERION = "kelly_criterion"
    FIXED_AMOUNT = "fixed_amount"
    FIXED_PERCENTAGE = "fixed_percentage"


class AlertSeverity(str, Enum):
    """
    Enumeration of alert severity levels for monitoring.
    """

    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


class PositionStatus(str, Enum):
    """
    Represents the state of a held position.
    """

    OPEN = "open"
    CLOSED = "closed"
