# src/trading_bot/core/models.py

from datetime import datetime
from typing import List, Optional

from sqlalchemy import (
    DateTime,
    Enum,
    ForeignKey,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

# Import the Base from our database setup
from .database import Base

# Import the enums we defined in core.enums
from .enums import AlertSeverity, OrderSide, OrderStatus, PositionStatus


class Market(Base):
    """
    SQLAlchemy ORM Model for storing market details.

    This table persists the static data from the
    MarketDetails Pydantic schema.
    """

    __tablename__ = "markets"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    # The unique ID from the exchange, e.g., "AAPL" or "MARKET-ABC-YES"
    market_id: Mapped[str] = mapped_column(
        String, unique=True, index=True, nullable=False
    )
    name: Mapped[str] = mapped_column(String, nullable=False)
    end_date: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    resolution_source: Mapped[Optional[str]] = mapped_column(String)

    # Timestamps for tracking when this record was created/updated
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), onupdate=func.now()
    )

    # Relationships
    orders: Mapped[List["OrderLog"]] = relationship("OrderLog", back_populates="market")
    trades: Mapped[List["TradeLog"]] = relationship("TradeLog", back_populates="market")

    def __repr__(self) -> str:
        return f"<Market(market_id='{self.market_id}', name='{self.name}')>"


class OrderLog(Base):
    """
    SQLAlchemy ORM Model for logging every order request and its state.

    This table tracks the full lifecycle of an order, combining data
    from the OrderRequest and ExecutionResult schemas.
    """

    __tablename__ = "order_logs"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    # This ID should be generated by our system or the exchange
    order_id: Mapped[str] = mapped_column(
        String, unique=True, index=True, nullable=False
    )
    market_id: Mapped[str] = mapped_column(
        String, ForeignKey("markets.market_id"), index=True, nullable=False
    )
    # Store the strategy name for performance attribution
    strategy_name: Mapped[Optional[str]] = mapped_column(String, index=True)

    # --- Data from OrderRequest ---
    side: Mapped[OrderSide] = mapped_column(Enum(OrderSide), nullable=False)
    requested_size: Mapped[float] = mapped_column(nullable=False)
    requested_price: Mapped[float] = mapped_column(nullable=False)

    # --- Data from ExecutionResult ---
    status: Mapped[OrderStatus] = mapped_column(
        Enum(OrderStatus), nullable=False, index=True
    )
    filled_size: Mapped[float] = mapped_column(default=0.0)
    avg_fill_price: Mapped[float] = mapped_column(default=0.0)

    # Timestamps for tracking the order's lifecycle
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), onupdate=func.now()
    )

    # Relationships
    market: Mapped["Market"] = relationship("Market", back_populates="orders")
    # One OrderLog can have many individual TradeLog entries (fills)
    trades: Mapped[List["TradeLog"]] = relationship("TradeLog", back_populates="order")

    def __repr__(self) -> str:
        return f"<OrderLog(order_id='{self.order_id}', status='{self.status}')>"


class TradeLog(Base):
    """
    SQLAlchemy ORM Model for logging individual fill events.

    This is a clean table of only executed trades, ideal for
    performance analysis and backtesting. Each entry represents
    a single fill (or partial fill).
    """

    __tablename__ = "trade_logs"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    # Link back to the order that generated this trade
    order_id: Mapped[Optional[str]] = mapped_column(
        String, ForeignKey("order_logs.order_id"), index=True
    )

    market_id: Mapped[str] = mapped_column(
        String, ForeignKey("markets.market_id"), index=True, nullable=False
    )
    side: Mapped[OrderSide] = mapped_column(Enum(OrderSide), nullable=False)

    # The size and price of this specific fill
    fill_size: Mapped[float] = mapped_column(nullable=False)
    fill_price: Mapped[float] = mapped_column(nullable=False)

    # Use server_default for DB-side timestamping
    fill_timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # Relationships
    order: Mapped[Optional["OrderLog"]] = relationship(
        "OrderLog", back_populates="trades"
    )
    market: Mapped["Market"] = relationship("Market", back_populates="trades")

    def __repr__(self) -> str:
        return (
            f"<TradeLog(id={self.id}, order_id='{self.order_id}', "
            f"size={self.fill_size} @ {self.fill_price})>"
        )


class EventLog(Base):
    """
    SQLAlchemy ORM Model for generic, text-based event logging.

    Used for monitoring, debugging, and persisting alerts.
    Maps to the Alert Pydantic schema.
    """

    __tablename__ = "event_logs"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), index=True
    )
    # The severity of the event (e.g., INFO, ERROR)
    severity: Mapped[AlertSeverity] = mapped_column(
        Enum(AlertSeverity), index=True, nullable=False
    )
    # The module that generated the log (e.g., 'StrategyEngine')
    source_module: Mapped[Optional[str]] = mapped_column(String, index=True)
    # Use Text for long log messages
    message: Mapped[str] = mapped_column(Text, nullable=False)

    def __repr__(self) -> str:
        return (
            f"<EventLog(timestamp='{self.timestamp}', "
            f"severity='{self.severity}', message='{self.message[:50]}...')>"
        )


class Position(Base):
    """
    SQLAlchemy ORM Model for persisting the bot's current positions.

    This table allows the Portfolio Manager to reconstruct its
    state after a restart.
    """

    __tablename__ = "positions"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    # market_id is now the sole unique identifier for the asset
    market_id: Mapped[str] = mapped_column(
        String, ForeignKey("markets.market_id"), index=True, nullable=False
    )

    # The current number of shares held
    size: Mapped[float] = mapped_column(nullable=False)
    # The average price at which the shares were acquired
    entry_price: Mapped[float] = mapped_column(nullable=False)

    # Tracks if the position is active or has been fully closed
    status: Mapped[PositionStatus] = mapped_column(
        Enum(PositionStatus), default=PositionStatus.OPEN, index=True
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), onupdate=func.now()
    )

    # Relationships
    market: Mapped["Market"] = relationship("Market")

    def __repr__(self) -> str:
        return (
            f"<Position(market_id='{self.market_id}', "
            f"size={self.size}, status='{self.status}')>"
        )
