# src/trading_bot/core/models.py


from sqlalchemy import (
    Column,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import relationship

# Import the Base from our database setup
from .database import Base

# Import the enums we defined in core.enums [cite: 233]
from .enums import AlertSeverity, MarketOutcome, OrderSide, OrderStatus


class Market(Base):
    """
    SQLAlchemy ORM Model for storing market details.

    This table persists the static data from the
    MarketDetails Pydantic schema. [cite: 253]
    """

    __tablename__ = "markets"

    id = Column(Integer, primary_key=True, index=True)
    # The unique ID from the exchange (e.g., Polymarket) [cite: 253]
    market_id = Column(String, unique=True, index=True, nullable=False)
    name = Column(String, nullable=False)
    end_date = Column(DateTime, nullable=False)
    resolution_source = Column(String)

    # Timestamps for tracking when this record was created/updated
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    orders = relationship("OrderLog", back_populates="market")
    trades = relationship("TradeLog", back_populates="market")

    def __repr__(self):
        return f"<Market(market_id='{self.market_id}', name='{self.name}')>"


class OrderLog(Base):
    """
    SQLAlchemy ORM Model for logging every order request and its state.

    This table tracks the full lifecycle of an order, combining data
    from the OrderRequest and ExecutionResult schemas.
    """

    __tablename__ = "order_logs"

    id = Column(Integer, primary_key=True, index=True)
    # This ID should be generated by our system or the exchange
    order_id = Column(String, unique=True, index=True, nullable=False)
    market_id = Column(
        String, ForeignKey("markets.market_id"), index=True, nullable=False
    )
    # Store the strategy name for performance attribution
    strategy_name = Column(String, index=True)

    # --- Data from OrderRequest ---
    side = Column(Enum(OrderSide), nullable=False)
    outcome = Column(Enum(MarketOutcome), nullable=False)
    requested_size = Column(Float, nullable=False)
    requested_price = Column(Float, nullable=False)

    # --- Data from ExecutionResult [cite: 270, 271, 272] ---
    status = Column(Enum(OrderStatus), nullable=False, index=True)
    filled_size = Column(Float, default=0.0)
    avg_fill_price = Column(Float, default=0.0)

    # Timestamps for tracking the order's lifecycle
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    market = relationship("Market", back_populates="orders")
    # One OrderLog can have many individual TradeLog entries (fills)
    trades = relationship("TradeLog", back_populates="order")

    def __repr__(self):
        return f"<OrderLog(order_id='{self.order_id}', status='{self.status}')>"


class TradeLog(Base):
    """
    SQLAlchemy ORM Model for logging individual fill events.

    This is a clean table of only executed trades, ideal for
    performance analysis and backtesting. Each entry represents
    a single fill (or partial fill).
    """

    __tablename__ = "trade_logs"

    id = Column(Integer, primary_key=True, index=True)
    # Link back to the order that generated this trade
    order_id = Column(String, ForeignKey("order_logs.order_id"), index=True)

    market_id = Column(
        String, ForeignKey("markets.market_id"), index=True, nullable=False
    )
    side = Column(Enum(OrderSide), nullable=False)
    outcome = Column(Enum(MarketOutcome), nullable=False)

    # The size and price of this specific fill
    fill_size = Column(Float, nullable=False)
    fill_price = Column(Float, nullable=False)

    # Use server_default for DB-side timestamping
    fill_timestamp = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    order = relationship("OrderLog", back_populates="trades")
    market = relationship("Market", back_populates="trades")

    def __repr__(self):
        return (
            f"<TradeLog(id={self.id}, order_id='{self.order_id}', "
            f"size={self.fill_size} @ {self.fill_price})>"
        )


class EventLog(Base):
    """
    SQLAlchemy ORM Model for generic, text-based event logging.

    Used for monitoring, debugging, and persisting alerts.
    Maps to the Alert Pydantic schema.
    """

    __tablename__ = "event_logs"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    # The severity of the event (e.g., INFO, ERROR)
    severity = Column(Enum(AlertSeverity), index=True, nullable=False)
    # The module that generated the log (e.g., 'StrategyEngine')
    source_module = Column(String, index=True)
    # Use Text for long log messages
    message = Column(Text, nullable=False)

    def __repr__(self):
        return (
            f"<EventLog(timestamp='{self.timestamp}', "
            f"severity='{self.severity}', message='{self.message[:50]}...')>"
        )
