# src/trading_bot/core/models.py

from datetime import datetime
from typing import List, Optional

from sqlalchemy import (
    JSON,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.orm import Mapped, declared_attr, mapped_column, relationship

# Import the Base from our database setup
from .database import Base

# Import the enums we defined in core.enums
from .enums import AlertSeverity, BarType, OrderSide, OrderStatus, PositionStatus


class Market(Base):
    """
    SQLAlchemy ORM Model for storing market details.

    This table persists the static data from the
    MarketDetails Pydantic schema.
    """

    __tablename__ = "markets"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    # The unique ID from the exchange, e.g., "AAPL" or "MARKET-ABC-YES"
    market_id: Mapped[str] = mapped_column(
        String, unique=True, index=True, nullable=False
    )
    name: Mapped[str] = mapped_column(String, nullable=False)
    end_date: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    resolution_source: Mapped[Optional[str]] = mapped_column(String)

    # Timestamps for tracking when this record was created/updated
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), onupdate=func.now()
    )

    # Relationships
    orders: Mapped[List["OrderLog"]] = relationship("OrderLog", back_populates="market")
    trades: Mapped[List["TradeLog"]] = relationship("TradeLog", back_populates="market")
    bars: Mapped[List["BarDataLog"]] = relationship(
        "BarDataLog", back_populates="market"
    )

    def __repr__(self) -> str:
        return f"<Market(market_id='{self.market_id}', name='{self.name}')>"


class BarDataLog(Base):
    """
    SQLAlchemy ORM Model for persisting OHLCV bar data.

    This table stores aggregated bar data (Time, Volume, or Dollar bars)
    for historical analysis and ML feature engineering.
    """

    __tablename__ = "bar_data_logs"

    __table_args__ = (
        UniqueConstraint(
            "market_id", "timestamp", "bar_type", "interval", name="uq_bar_data_log"
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    market_id: Mapped[str] = mapped_column(
        String, ForeignKey("markets.market_id"), index=True, nullable=False
    )
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), index=True, nullable=False
    )

    open: Mapped[float] = mapped_column(nullable=False)
    high: Mapped[float] = mapped_column(nullable=False)
    low: Mapped[float] = mapped_column(nullable=False)
    close: Mapped[float] = mapped_column(nullable=False)
    volume: Mapped[float] = mapped_column(nullable=False)

    bar_type: Mapped[BarType] = mapped_column(Enum(BarType), nullable=False, index=True)
    interval: Mapped[Optional[str]] = mapped_column(String, nullable=True, index=True)
    ticks_count: Mapped[int] = mapped_column(nullable=False)
    dollar_volume: Mapped[float] = mapped_column(nullable=False)

    # Relationships
    market: Mapped["Market"] = relationship("Market", back_populates="bars")

    def __repr__(self) -> str:
        return (
            f"<BarDataLog(market_id='{self.market_id}', "
            f"timestamp='{self.timestamp}', type='{self.bar_type}')>"
        )


class OrderLog(Base):
    """
    SQLAlchemy ORM Model for logging every order request and its state.

    This table tracks the full lifecycle of an order, combining data
    from the OrderRequest and ExecutionResult schemas.
    """

    __tablename__ = "order_logs"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    # This ID should be generated by our system or the exchange
    order_id: Mapped[str] = mapped_column(
        String, unique=True, index=True, nullable=False
    )
    run_id: Mapped[Optional[str]] = mapped_column(String, index=True)
    market_id: Mapped[str] = mapped_column(
        String, ForeignKey("markets.market_id"), index=True, nullable=False
    )
    # Store the strategy name for performance attribution
    strategy_name: Mapped[Optional[str]] = mapped_column(String, index=True)

    # --- Data from OrderRequest ---
    side: Mapped[OrderSide] = mapped_column(Enum(OrderSide), nullable=False)
    outcome: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    requested_size: Mapped[float] = mapped_column(nullable=False)
    requested_price: Mapped[float] = mapped_column(nullable=False)

    # --- Data from ExecutionResult ---
    status: Mapped[OrderStatus] = mapped_column(
        Enum(OrderStatus), nullable=False, index=True
    )
    filled_size: Mapped[float] = mapped_column(default=0.0)
    avg_fill_price: Mapped[float] = mapped_column(default=0.0)

    # Timestamps for tracking the order's lifecycle
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), onupdate=func.now()
    )

    # Relationships
    market: Mapped["Market"] = relationship("Market", back_populates="orders")
    # One OrderLog can have many individual TradeLog entries (fills)
    trades: Mapped[List["TradeLog"]] = relationship("TradeLog", back_populates="order")

    def __repr__(self) -> str:
        return f"<OrderLog(order_id='{self.order_id}', status='{self.status}')>"


class TradeLog(Base):
    """
    SQLAlchemy ORM Model for logging individual fill events.

    This is a clean table of only executed trades, ideal for
    performance analysis and backtesting. Each entry represents
    a single fill (or partial fill).
    """

    __tablename__ = "trade_logs"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    run_id: Mapped[Optional[str]] = mapped_column(String, index=True)
    # Link back to the order that generated this trade
    order_id: Mapped[Optional[str]] = mapped_column(
        String, ForeignKey("order_logs.order_id"), index=True
    )

    market_id: Mapped[str] = mapped_column(
        String, ForeignKey("markets.market_id"), index=True, nullable=False
    )
    side: Mapped[OrderSide] = mapped_column(Enum(OrderSide), nullable=False)
    outcome: Mapped[Optional[str]] = mapped_column(String, nullable=True)

    # The size and price of this specific fill
    fill_size: Mapped[float] = mapped_column(nullable=False)
    fill_price: Mapped[float] = mapped_column(nullable=False)

    # Use server_default for DB-side timestamping
    fill_timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # Relationships
    order: Mapped[Optional["OrderLog"]] = relationship(
        "OrderLog", back_populates="trades"
    )
    market: Mapped["Market"] = relationship("Market", back_populates="trades")

    def __repr__(self) -> str:
        return (
            f"<TradeLog(id={self.id}, order_id='{self.order_id}', "
            f"size={self.fill_size} @ {self.fill_price})>"
        )


class EventLog(Base):
    """
    SQLAlchemy ORM Model for generic, text-based event logging.

    Used for monitoring, debugging, and persisting alerts.
    Maps to the Alert Pydantic schema.
    """

    __tablename__ = "event_logs"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), index=True
    )
    # The severity of the event (e.g., INFO, ERROR)
    severity: Mapped[AlertSeverity] = mapped_column(
        Enum(AlertSeverity), index=True, nullable=False
    )
    # The module that generated the log (e.g., 'StrategyEngine')
    source_module: Mapped[Optional[str]] = mapped_column(String, index=True)
    # Use Text for long log messages
    message: Mapped[str] = mapped_column(Text, nullable=False)

    def __repr__(self) -> str:
        return (
            f"<EventLog(timestamp='{self.timestamp}', "
            f"severity='{self.severity}', message='{self.message[:50]}...')>"
        )


class Position(Base):
    """
    SQLAlchemy ORM Model for persisting the bot's current positions.

    This table allows the Portfolio Manager to reconstruct its
    state after a restart.
    """

    __tablename__ = "positions"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    run_id: Mapped[Optional[str]] = mapped_column(String, index=True)
    # market_id is now the sole unique identifier for the asset
    market_id: Mapped[str] = mapped_column(
        String, ForeignKey("markets.market_id"), index=True, nullable=False
    )
    outcome: Mapped[Optional[str]] = mapped_column(String, nullable=True)

    # The current number of shares held
    size: Mapped[float] = mapped_column(nullable=False)
    # The average price at which the shares were acquired
    entry_price: Mapped[float] = mapped_column(nullable=False)

    # Tracks if the position is active or has been fully closed
    status: Mapped[PositionStatus] = mapped_column(
        Enum(PositionStatus), default=PositionStatus.OPEN, index=True
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), onupdate=func.now()
    )

    # Relationships
    market: Mapped["Market"] = relationship("Market")

    def __repr__(self) -> str:
        return (
            f"<Position(market_id='{self.market_id}', outcome='{self.outcome}', "
            f"size={self.size}, status='{self.status}')>"
        )


class PredictionLog(Base):
    """
    SQLAlchemy ORM Model for machine learning prediction logs.
    Maps all prediction logs to a single table.
    """

    __tablename__ = "prediction_logs"

    __table_args__ = (
        UniqueConstraint(
            "timestamp",
            "market_id",
            "strategy_name",
            "run_id",
            "log_type",
            name="uq_prediction_log",
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    run_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), index=True, nullable=False
    )
    strategy_name: Mapped[str] = mapped_column(String, index=True, nullable=False)

    # Store model outputs (probabilities or predicted values) as JSON string
    prediction_output: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Store final signal decision and confidence
    predicted_signal: Mapped[str] = mapped_column(String, nullable=False)
    confidence: Mapped[float] = mapped_column(nullable=False)

    # Optional actual outcome for visual analysis
    actual_future_return: Mapped[Optional[float]] = mapped_column(nullable=True)

    market_id: Mapped[str] = mapped_column(
        String, ForeignKey("markets.market_id"), index=True, nullable=False
    )
    market: Mapped["Market"] = relationship("Market")

    log_type: Mapped[str] = mapped_column(String, index=True, nullable=False)

    __mapper_args__ = {
        "polymorphic_on": "log_type",
        "polymorphic_identity": "base",
    }


class ModelPredictionLog(PredictionLog):
    """Logs predictions generated during live/paper trading."""

    __mapper_args__ = {
        "polymorphic_identity": "live",
    }

    def __repr__(self) -> str:
        return (
            f"<ModelPredictionLog(run_id='{self.run_id}', market_id='{self.market_id}', "
            f"strategy='{self.strategy_name}', signal='{self.predicted_signal}')>"
        )


class BacktestPredictionLog(PredictionLog):
    """Logs predictions generated during historical simulation backtests."""

    __mapper_args__ = {
        "polymorphic_identity": "backtest",
    }

    def __repr__(self) -> str:
        return (
            f"<BacktestPredictionLog(run_id='{self.run_id}', market_id='{self.market_id}', "
            f"strategy='{self.strategy_name}', signal='{self.predicted_signal}')>"
        )


class BacktestEquityLog(Base):
    """Logs cash, position size, and overall equity per tick for a backtest simulation run."""

    __tablename__ = "backtest_equity_logs"

    __table_args__ = (
        UniqueConstraint(
            "timestamp",
            "run_id",
            name="uq_backtest_equity_log",
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    run_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), index=True, nullable=False
    )
    cash: Mapped[float] = mapped_column(nullable=False)
    position: Mapped[float] = mapped_column(nullable=False)
    close: Mapped[float] = mapped_column(nullable=False)
    equity: Mapped[float] = mapped_column(nullable=False)

    def __repr__(self) -> str:
        return (
            f"<BacktestEquityLog(run_id='{self.run_id}', timestamp='{self.timestamp}', "
            f"equity={self.equity:.2f})>"
        )


class TimeSeriesDataset(Base):
    """
    SQLAlchemy ORM Model representing a dataset.
    Identifies a specific versioned slice of time-series bar data.
    """

    __tablename__ = "time_series_datasets"

    dataset_id: Mapped[str] = mapped_column(String, primary_key=True, index=True)
    market_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    interval: Mapped[str] = mapped_column(String, index=True, nullable=False)
    start_time: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    end_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    hash: Mapped[str] = mapped_column(String, unique=True, index=True, nullable=False)

    def __repr__(self) -> str:
        return f"<TimeSeriesDataset(dataset_id='{self.dataset_id}', market_id='{self.market_id}', interval='{self.interval}')>"


class ModelRegistryLog(Base):
    """
    SQLAlchemy ORM Model representing the model registry.
    Stores metadata, serialized paths, hyperparameters, and evaluation metrics.
    """

    __tablename__ = "model_registry"

    __table_args__ = (
        Index(
            "ix_model_registry_signature",
            "model_type",
            "market_id",
            "interval",
            "horizon",
            "status",
        ),
        Index(
            "uq_production_model_signature",
            "model_type",
            "market_id",
            "interval",
            "horizon",
            unique=True,
            sqlite_where=text("status = 'production'"),
        ),
    )

    model_id: Mapped[str] = mapped_column(String, primary_key=True, index=True)
    run_id: Mapped[Optional[str]] = mapped_column(String, index=True, nullable=True)
    model_type: Mapped[str] = mapped_column(String, index=True, nullable=False)
    market_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    interval: Mapped[str] = mapped_column(String, index=True, nullable=False)
    horizon: Mapped[int] = mapped_column(Integer, index=True, nullable=False)

    dataset_id: Mapped[Optional[str]] = mapped_column(
        String, ForeignKey("time_series_datasets.dataset_id"), nullable=True, index=True
    )
    dataset: Mapped[Optional["TimeSeriesDataset"]] = relationship("TimeSeriesDataset")

    onnx_path: Mapped[str] = mapped_column(String, nullable=False)
    hyperparameters: Mapped[dict] = mapped_column(JSON, nullable=False)
    metrics: Mapped[dict] = mapped_column(JSON, nullable=False)
    status: Mapped[str] = mapped_column(String, default="candidate", index=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), onupdate=func.now()
    )

    def __repr__(self) -> str:
        return f"<ModelRegistryLog(model_id='{self.model_id}', type='{self.model_type}', status='{self.status}')>"
